- id: '1582894309852'
  alias: Welcome Home
  description: Light turns on at night when the door is unlocked
  trigger:
  - entity_id: lock.front_door_lock_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: and
    conditions:
    - condition: state
      entity_id: light.downstairs
      state: 'off'
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.front_door_lock_alarm_type
      state: '19'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.front_door_lock_alarm_type
        state: '22'
  action:
  - data: {}
    entity_id: light.kitchen
    service: light.turn_on
- id: '1585781804427'
  alias: Powder Room Lights On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 25b27714c4400d63c2e62694f42181ef
    entity_id: binary_sensor.multisensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
  action:
  - type: turn_on
    device_id: d0ecb560ff75cbfc25cac75403b36e52
    entity_id: light.powder_room_1
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 5295319a041d40dfbc690f9e04ea9fd1
    entity_id: light.powder_room_2
    domain: light
    brightness_pct: 100
  mode: single
- id: '1585781880464'
  alias: Powder Room Lights Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 25b27714c4400d63c2e62694f42181ef
    entity_id: binary_sensor.multisensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
  action:
  - type: turn_off
    device_id: d0ecb560ff75cbfc25cac75403b36e52
    entity_id: light.powder_room_1
    domain: light
  - type: turn_off
    device_id: 5295319a041d40dfbc690f9e04ea9fd1
    entity_id: light.powder_room_2
    domain: light
  mode: single
- id: '1587610014345'
  alias: Exterior Sunset
  description: Automate the functionality of the exterior lights to turn on at sunset.
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - type: turn_on
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 5ff1104372fd3dd1059beecaf386a322
    entity_id: light.front_stoop
    domain: light
    brightness_pct: 100
  mode: single
- id: '1587610079072'
  alias: Exterior Sunrise
  description: Automate the functionality of the exterior lights to turn off at sunrise.
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - type: turn_off
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
  - type: turn_off
    device_id: 5ff1104372fd3dd1059beecaf386a322
    entity_id: light.front_stoop
    domain: light
  mode: single
- id: '1589588967075'
  alias: Hallway Night Lights On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: switch.turn_on
    target:
      device_id:
      - 7b0b4fe6b9c656f4c0e67ca65f5a26ca
      - c264b09466926376bfa7d2860feec206
  mode: single
- id: '1589589008880'
  alias: Hallway Nightlight Turn Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: switch.turn_off
    target:
      device_id:
      - 7b0b4fe6b9c656f4c0e67ca65f5a26ca
      - c264b09466926376bfa7d2860feec206
  mode: single
- id: '1651539763507'
  alias: Small Tank Light - On
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition:
  - condition: device
    type: is_off
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  action:
  - type: turn_on
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  mode: single
- id: '1651539818720'
  alias: Small Tank Light - Off
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: device
    type: is_on
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  action:
  - type: turn_off
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  mode: single
- id: '1653951135024'
  alias: Turn Powder Room Back On
  description: If someone turns off the switch for the Powder Room lights, it needs
    to be reset for the automations to work
  trigger:
  - platform: device
    type: turned_off
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - type: turn_on
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - type: turn_off
    device_id: d0ecb560ff75cbfc25cac75403b36e52
    entity_id: light.powder_room_1
    domain: light
  - type: turn_off
    device_id: 5295319a041d40dfbc690f9e04ea9fd1
    entity_id: light.powder_room_2
    domain: light
  mode: single
