- id: '1582894309852'
  alias: Welcome Home
  description: Light turns on at night when the door is unlocked
  trigger:
  - event_data:
      domain: lock
      service: unlock
      service_data:
        code: 8402837
        node_id: 10
    event_type: call_service
    platform: event
  condition: []
  action:
  - condition: state
    entity_id: switch.leviton_dz15s_1bz_decora_smart_switch_switch
    state: 'off'
  - device_id: 8269d212b16845b49415ddca80aa873c
    domain: switch
    entity_id: switch.leviton_dz15s_1bz_decora_smart_switch_switch
    type: turn_on
  - device_id: 52d632041f174aabaea7bbd57907f0da
    domain: light
    entity_id: light.kitchen_1
    type: turn_on
  - device_id: 378c7ac9a8ca4558882860861aa0390b
    domain: light
    entity_id: light.kitchen_2
    type: turn_on
- id: '1585781804427'
  alias: Powder Room Lights On
  description: ''
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '0'
    platform: state
    to: '8'
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '3'
    platform: state
    to: '8'
  condition:
  - condition: device
    device_id: 528e2dcab06a47d6bfa20c1c23711dcc
    domain: light
    entity_id: light.powder_room_1
    type: is_off
  - condition: device
    device_id: 91a52e7570ca45a3a608ca286bd24bbf
    domain: light
    entity_id: light.powder_room_2
    type: is_off
  action:
  - device_id: 528e2dcab06a47d6bfa20c1c23711dcc
    domain: light
    entity_id: light.powder_room_1
    type: turn_on
  - device_id: 91a52e7570ca45a3a608ca286bd24bbf
    domain: light
    entity_id: light.powder_room_2
    type: turn_on
- id: '1585781880464'
  alias: Powder Room Lights Off
  description: ''
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '8'
    platform: state
    to: '0'
  condition:
  - condition: device
    device_id: 528e2dcab06a47d6bfa20c1c23711dcc
    domain: light
    entity_id: light.powder_room_1
    type: is_on
  - condition: device
    device_id: 91a52e7570ca45a3a608ca286bd24bbf
    domain: light
    entity_id: light.powder_room_2
    type: is_on
  action:
  - device_id: 528e2dcab06a47d6bfa20c1c23711dcc
    domain: light
    entity_id: light.powder_room_1
    type: turn_off
  - device_id: 91a52e7570ca45a3a608ca286bd24bbf
    domain: light
    entity_id: light.powder_room_2
    type: turn_off
