- id: '1582894309852'
  alias: Welcome Home
  description: Light turns on at night when the door is unlocked
  trigger:
  - entity_id: lock.kwikset_spectrum_brands_touchpad_electronic_deadbolt_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: and
    conditions:
    - condition: state
      entity_id: light.downstairs
      state: 'off'
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.kwikset_spectrum_brands_touchpad_electronic_deadbolt_alarm_type
      state: '19'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.kwikset_spectrum_brands_touchpad_electronic_deadbolt_alarm_type
        state: '22'
  action:
  - data: {}
    entity_id: light.kitchen
    service: light.turn_on
- id: '1585781804427'
  alias: Powder Room Lights On
  description: ''
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '0'
    platform: state
    to: '8'
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '3'
    platform: state
    to: '8'
  condition:
  - condition: state
    entity_id: light.powder_room
    state: 'off'
  action:
  - data: {}
    entity_id: light.powder_room
    service: light.turn_on
- id: '1585781880464'
  alias: Powder Room Lights Off
  description: ''
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    from: '8'
    platform: state
    to: '0'
  condition:
  - condition: state
    entity_id: light.powder_room
    state: 'on'
  action:
  - data: {}
    entity_id: light.powder_room
    service: light.turn_off
- id: '1587610014345'
  alias: Exterior Sunset
  description: Automate the functionality of the exterior lights to turn on at sunset.
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id:
    - light.back_yard
    - light.front_stoop
    service: light.turn_on
- id: '1587610079072'
  alias: Exterior Sunrise
  description: Automate the functionality of the exterior lights to turn off at sunrise.
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.back_yard,light.front_stoop
    service: light.turn_off
- id: '1589588967075'
  alias: Hallway Night Lights On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: a61094cd8fda4f8dbab0b14607f8a17c
    domain: switch
    entity_id: switch.jasco_products_14288_duplex_receptacle_switch_3
    type: turn_on
  - device_id: 2ffc8973483749fea9702fa4ff756baf
    domain: switch
    entity_id: switch.jasco_products_14288_duplex_receptacle_switch_2
    type: turn_on
- id: '1589589008880'
  alias: Hallway Nightlight Turn Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - device_id: 2ffc8973483749fea9702fa4ff756baf
    domain: switch
    entity_id: switch.jasco_products_14288_duplex_receptacle_switch_2
    type: turn_off
  - device_id: a61094cd8fda4f8dbab0b14607f8a17c
    domain: switch
    entity_id: switch.jasco_products_14288_duplex_receptacle_switch_3
    type: turn_off
