- id: '1582894309852'
  alias: Welcome Home
  description: Light turns on at night when the door is unlocked
  trigger:
  - entity_id: lock.front_door_lock_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: and
    conditions:
    - condition: state
      entity_id: light.downstairs
      state: 'off'
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.front_door_lock_alarm_type
      state: '19'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.front_door_lock_alarm_type
        state: '22'
  action:
  - data: {}
    entity_id: light.kitchen
    service: light.turn_on
- id: '1585781804427'
  alias: Powder Room Lights On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 25b27714c4400d63c2e62694f42181ef
    entity_id: binary_sensor.powder_room_multisensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
  action:
  - type: turn_on
    device_id: d0ecb560ff75cbfc25cac75403b36e52
    entity_id: light.powder_room_1
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 5295319a041d40dfbc690f9e04ea9fd1
    entity_id: light.powder_room_2
    domain: light
    brightness_pct: 100
  mode: single
- id: '1585781880464'
  alias: Powder Room Lights Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 25b27714c4400d63c2e62694f42181ef
    entity_id: binary_sensor.powder_room_multisensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
  action:
  - type: turn_off
    device_id: d0ecb560ff75cbfc25cac75403b36e52
    entity_id: light.powder_room_1
    domain: light
  - type: turn_off
    device_id: 5295319a041d40dfbc690f9e04ea9fd1
    entity_id: light.powder_room_2
    domain: light
  mode: single
- id: '1587610014345'
  alias: Exterior Sunset
  description: Automate the functionality of the exterior lights to turn on at sunset.
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - type: turn_on
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 5ff1104372fd3dd1059beecaf386a322
    entity_id: light.front_stoop
    domain: light
    brightness_pct: 100
  mode: single
- id: '1587610079072'
  alias: Exterior Sunrise
  description: Automate the functionality of the exterior lights to turn off at sunrise.
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - type: turn_off
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
  - type: turn_off
    device_id: 5ff1104372fd3dd1059beecaf386a322
    entity_id: light.front_stoop
    domain: light
  mode: single
- id: '1589588967075'
  alias: Hallway Night Lights On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - type: turn_on
    device_id: 84cd559d004b11e39914b276220b4ca9
    entity_id: switch.hallway_outlet_2_2
    domain: switch
  - type: turn_on
    device_id: 4c0741fdcd556bb253776da223d496eb
    entity_id: switch.hallway_outlet_3_3
    domain: switch
  mode: single
- id: '1589589008880'
  alias: Hallway Nightlight Turn Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - type: turn_off
    device_id: 84cd559d004b11e39914b276220b4ca9
    entity_id: switch.hallway_outlet_2_2
    domain: switch
  - type: turn_off
    device_id: 4c0741fdcd556bb253776da223d496eb
    entity_id: switch.hallway_outlet_3_3
    domain: switch
  mode: single
- id: '1651539763507'
  alias: Small Tank Light - On
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition:
  - condition: device
    type: is_off
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  action:
  - type: turn_on
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  mode: single
- id: '1651539818720'
  alias: Small Tank Light - Off
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: device
    type: is_on
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  action:
  - type: turn_off
    device_id: 885a9903367bf9344788137d40d6360e
    entity_id: switch.right_outlet_1
    domain: switch
  mode: single
- id: '1653951135024'
  alias: Turn Powder Room Back On
  description: If someone turns off the switch for the Powder Room lights, it needs
    to be reset for the automations to work
  trigger:
  - platform: device
    type: turned_off
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - type: turn_on
    device_id: 60820c05d03da4a39b6303907759f69a
    entity_id: switch.powder_room_light_switch_3
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - type: turn_off
    device_id: d0ecb560ff75cbfc25cac75403b36e52
    entity_id: light.powder_room_1
    domain: light
  - type: turn_off
    device_id: 5295319a041d40dfbc690f9e04ea9fd1
    entity_id: light.powder_room_2
    domain: light
  mode: single
- id: '1654053995550'
  alias: Ink Low Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ink_level_black
    below: '15'
  condition: []
  action:
  - service: notify.notify
    data:
      message: "{% for inkLevel in [states.sensor.ink_level_black, states.sensor.ink_level_cyan,
        states.sensor.ink_level_magenta, states.sensor.ink_level_yellow] %}\n  {%-
        if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}}
        is 10% or below\n{% endfor %}"
  - device_id: 487b1921e673eac8b31e3064b4c37283
    domain: light
    entity_id: light.living_room_lamp_1
    type: flash
  mode: parallel
  max: 4
- id: '1656519350500'
  alias: Utility Closet Light On
  description: ''
  trigger:
  - type: unsafe
    platform: device
    device_id: cb62048df0d19dd5d8cca8d3ae6f7555
    entity_id: binary_sensor.utility_closet_door_home_security_intrusion
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 549cac0be87ec5edc7124985e60922b1
    entity_id: light.utility_closet_light_group
    domain: light
  mode: single
- id: '1656519388457'
  alias: Utility Closet Light Off
  description: ''
  trigger:
  - type: not_unsafe
    platform: device
    device_id: cb62048df0d19dd5d8cca8d3ae6f7555
    entity_id: binary_sensor.utility_closet_door_home_security_intrusion
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: 549cac0be87ec5edc7124985e60922b1
    entity_id: light.utility_closet_light_group
    domain: light
  mode: single
- id: '1659402951897'
  alias: Open gate triggers back light
  description: ''
  trigger:
  - type: unsafe
    platform: device
    device_id: 620645699e6f48906040f178f9bd8384
    entity_id: binary_sensor.back_gate_home_security_intrusion
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
  - condition: device
    type: is_off
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
  action:
  - type: turn_on
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
    brightness_pct: 100
  mode: single
- id: '1659405626897'
  alias: Turn Off Back Stoop Light
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - type: is_not_unsafe
    condition: device
    device_id: 620645699e6f48906040f178f9bd8384
    entity_id: binary_sensor.back_gate_home_security_intrusion
    domain: binary_sensor
  - type: is_not_unsafe
    condition: device
    device_id: 2df50b177680f3297c511c9e3d8946f4
    entity_id: binary_sensor.sliding_glass_door_home_security_intrusion
    domain: binary_sensor
  action:
  - type: turn_off
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
  mode: restart
- id: '1672610785691'
  alias: Sliding Door turns on back stoop light
  description: ''
  trigger:
  - type: unsafe
    platform: device
    device_id: 2df50b177680f3297c511c9e3d8946f4
    entity_id: binary_sensor.sliding_glass_door_home_security_intrusion
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
  - condition: device
    type: is_off
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
  action:
  - type: turn_on
    device_id: e72bb4040c082ba0dd083ac4ae5eb12e
    entity_id: light.back_stoop
    domain: light
    brightness_pct: 100
  mode: single
- id: '1687812758984'
  alias: Back Gate Notification
  description: making sure I know someone has entered the property from the back gate
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.back_gate_home_security_intrusion
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      title: Alert
      message: Back gate has been opened
  mode: single
- id: '1742312948319'
  alias: Restart on Expiry
  description: Restart HA Core to refresh DNS Cert
  triggers:
  - trigger: state
    entity_id:
    - sensor.opsmart_duckdns_org_cert_expiry
    attribute: is_valid
    to: false
  conditions: []
  actions:
  - device_id: 8f834c195c589cd189cfcee4b99d93e0
    domain: mobile_app
    type: notify
    message: DuckDNS Cert has expired.  System restart triggered.
    title: System Restart
  - action: homeassistant.restart
    metadata: {}
    data: {}
  mode: single
