- id: '1582894309852'
  alias: Welcome Home
  description: Light turns on at night when the door is unlocked
  trigger:
  - entity_id: lock.front_door_lock_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: and
    conditions:
    - condition: state
      entity_id: light.downstairs
      state: 'off'
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.front_door_lock_alarm_type
      state: '19'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.front_door_lock_alarm_type
        state: '22'
  action:
  - data: {}
    entity_id: light.kitchen
    service: light.turn_on
- id: '1585781804427'
  alias: Powder Room Lights On
  description: ''
  trigger:
  - entity_id: sensor.powder_room_monitor_burglar
    from: '0'
    platform: state
    to: '8'
  - entity_id: sensor.powder_room_monitor_burglar
    from: '3'
    platform: state
    to: '8'
  condition:
  - condition: state
    entity_id: switch.powder_room_switch_1
    state: 'off'
  action:
  - service: switch.turn_on
    target:
      device_id: 28703b5969711ef4fe7136c4edeb4cfb
  mode: single
- id: '1585781880464'
  alias: Powder Room Lights Off
  description: ''
  trigger:
  - entity_id: sensor.powder_room_burglar
    from: '8'
    platform: state
    to: '0'
  condition:
  - condition: state
    entity_id: switch.powder_room_switch_1
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      device_id: 28703b5969711ef4fe7136c4edeb4cfb
  mode: single
- id: '1587610014345'
  alias: Exterior Sunset
  description: Automate the functionality of the exterior lights to turn on at sunset.
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: switch.turn_on
    target:
      device_id:
      - f44c88cfa452208c7c5c3d24e586d7ef
      - 32006187b361064b5de53bfb683dc24b
  mode: single
- id: '1587610079072'
  alias: Exterior Sunrise
  description: Automate the functionality of the exterior lights to turn off at sunrise.
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: switch.turn_off
    target:
      device_id:
      - 32006187b361064b5de53bfb683dc24b
      - f44c88cfa452208c7c5c3d24e586d7ef
  mode: single
- id: '1589588967075'
  alias: Hallway Night Lights On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: switch.turn_on
    target:
      device_id:
      - 7b0b4fe6b9c656f4c0e67ca65f5a26ca
      - c264b09466926376bfa7d2860feec206
  mode: single
- id: '1589589008880'
  alias: Hallway Nightlight Turn Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: switch.turn_off
    target:
      device_id:
      - 7b0b4fe6b9c656f4c0e67ca65f5a26ca
      - c264b09466926376bfa7d2860feec206
  mode: single
