# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant: 
  auth_providers: !include authentication/default.yaml
  auth_mfa_modules: !include authentication/mfa_config.yaml
  # http: !include authentication/http_config.yaml
  customize: !include_dir_named customizations/
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: !secret zone_home_elev
  unit_system: imperial
  time_zone: America/New_York
  name: 841 N 4th

# Enablers
browser:
config:
conversation:
# discovery: // prefer manual configuration
frontend:
  javascript_version: latest
# ios:
lovelace:
  mode: yaml
map:
mobile_app:
sun:
updater:
  include_used_components: true
system_health:

## Text to speech
tts: !include integrations/tts/tts_config.yaml

### House Settings
# areas: !include area_config.yaml
automation: !include automations.yaml
group: !include_dir_merge_named groups/
history:
# history_graph: !include history_graph_config.yaml
input_number: !include_dir_merge_named inputs/number/
input_select: !include_dir_merge_named inputs/select/
person: !include person_config.yaml
# scene: !include scenes.yaml 
# script: !include scripts.yaml
switch: !include_dir_merge_list switches/
zone: !include zone_config.yaml

### Integrations
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
cast: !include integrations/media/google_cast.yaml
# device_sun_light_trigger: !include integrations/environment/tracker_sun_light_config.yaml // Needs more customization
device_tracker: !include tracker_device_config.yaml
hacs: !include integrations/environment/hacs_config.yaml
hue: !include integrations/lights/hue_config.yaml
jewish_calendar: !include integrations/environment/jewish_calendar_config.yaml
local_ip:
media_player: !include_dir_merge_list integrations/media_players/
mqtt: !include integrations/network/mqtt_config.yaml
# nest: !include integrations/climate_control/nest_config.yaml
plex: !include integrations/media/plex_config.yaml
remote: !include integrations/remotes/harmony_config.yaml
# roomba: !include integrations/cleaning/roomba_config.yaml // Did not work, opted for 'vacuum' integration instead
sensor: !include_dir_merge_list integrations/sensors/
# upnp: !include integrations/network/upnp_config.yaml
vacuum: !include integrations/cleaning/vacuum_config.yaml
# vera: !include integrations/zwave/vera_config.yaml
weather: !include_dir_merge_list integrations/weather/
zwave: !include integrations/zwave/zwave_config.yaml
