# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 20
  unit_system: imperial
  time_zone: America/New_York
  name: 841 N 4th

# Enablers
browser:
config:
conversation:
discovery:
frontend:
  javascript_version: latest
# ios:
map:
mobile_app:
sun:
updater:
  include_used_components: true
system_health:

## Text to speech
tts:
  - platform: google_translate

### House Settings
automation: !include automations.yaml
group: !include groups.yaml
person: !include person_config.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
## Zones
zone: !include zone_config.yaml

### Integrations
# device_sun_light_trigger: !include sunlight_tracker.yaml
device_tracker: !include tracker_device_config.yaml
weather: !include_dir_merge_list integrations/weather
# ZWave Network
zwave:
  usb_path: /dev/ttyACM0
  network_key: 0x9F, 0x42, 0x29, 0x63, 0xDD, 0x2E, 0x46, 0x07, 0x4D, 0xD5, 0x2C, 0x8E, 0xCE, 0xF6, 0x33, 0x61
  device_config: !include integrations/zwave/zwave_device_config.yaml
