# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  auth_providers: !include authentication/default.yaml
  auth_mfa_modules: !include authentication/mfa_config.yaml
  customize: !include_dir_named customizations/
  external_url: !secret external_url
  internal_url: !secret internal_url
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: !secret zone_home_elev
  unit_system: imperial
  time_zone: America/New_York
  name: 841 N 4th

# External
duckdns: !include authentication/duckdns_config.yaml
http: !include authentication/http_config.yaml

# Enablers
browser:
config:
conversation:
# discovery: // prefer manual configuration
frontend:
# https://www.home-assistant.io/integrations/ios/
# ios: // only need if more than 1 iPhone user needs the app. no use case now
## UI Configuration
# https://www.home-assistant.io/lovelace/dashboards-and-views/
lovelace: !include app/config/ui-config.yaml
map:
mobile_app:
sun:
updater:
system_health:

## Text to speech
tts: !include integrations/tts/tts_config.yaml

### House Settings
# areas: !include area_config.yaml
automation: !include automations.yaml
group: !include_dir_merge_named groups/
history:
# history_graph: !include history_graph_config.yaml
input_number: !include_dir_named app/inputs/number/
input_select: !include_dir_named app/inputs/select/
###
# Config file for People tracked in the House
# https://www.home-assistant.io/integrations/person/
###
person: !include_dir_list people/
scene: !include_dir_merge_list scenes/
# script: !include scripts.yaml
switch: !include_dir_merge_list app/switches/
zone: !include_dir_list locations/

### Integrations
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
# cast: !include integrations/media/google_cast.yaml
# device_sun_light_trigger: !include integrations/environment/tracker_sun_light_config.yaml # Needs more customization
device_tracker: !include device_tracker_config.yaml
# hacs: !include integrations/environment/hacs_config.yaml
hue: !include integrations/lights/hue_config.yaml
jewish_calendar: !include integrations/environment/jewish_calendar_config.yaml
lifx: !include integrations/lights/lifx_config.yaml
media_player: !include_dir_merge_list integrations/media_players/
# nest: !include integrations/climate_control/nest_config.yaml
plex: !include integrations/media/plex_config.yaml
# roomba: !include integrations/cleaning/roomba_config.yaml # Used Automatic Installation
sensor: !include_dir_merge_list integrations/sensors/
# upnp: !include integrations/network/upnp_config.yaml
# vacuum: !include integrations/cleaning/vacuum_config.yaml # Used Automatic Installation
weather: !include_dir_list integrations/weather/
zwave: !include integrations/zwave/zwave_config.yaml
### MQTT Config Section
# mqtt: !include integrations/network/mqtt_config.yaml
# lock: !include integrations/network/mqtt_lock.yaml
