# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant: 
  # auth_providers: !include authentication.yaml
  customize: !include customizations.yaml
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 20
  unit_system: imperial
  time_zone: America/New_York
  name: 841 N 4th

# Enablers
browser:
config:
conversation:
# discovery:
frontend:
  javascript_version: latest
# ios:
map:
mobile_app:
sun:
updater:
  include_used_components: true
system_health:

## Text to speech
tts:
  - platform: google_translate

### House Settings
# areas: !include area_config.yaml
automation: !include automations.yaml
# group: !include groups.yaml
history:
# history_graph: !include history_graph_config.yaml
input_select: !include_dir_merge_list inputs/select/
local_ip:
  name: localhost
person: !include person_config.yaml
# scene: !include scenes.yaml
# script: !include scripts.yaml
## Zones
zone: !include zone_config.yaml

### Integrations
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
cast: !include integrations/media/google_cast.yaml
# device_sun_light_trigger: !include sunlight_tracker.yaml
device_tracker: !include tracker_device_config.yaml
hue: !include integrations/lights/hue_config.yaml
jewish_calendar: !include_dir_merge_list integrations/environment/jewish_calendar_config.yaml
media_player: !include_dir_merge_list integrations/media_players/
# nest: !include integrations/climate_control/nest_config.yaml
# remote: !include integrations/remotes/harmony_config.yaml
sensor: !include_dir_merge_list integrations/sensors/
switch: !include_dir_merge_list integrations/switch/
weather: !include_dir_merge_list integrations/weather/
upnp: !include integrations/network/upnp_config.yaml
# vacuum: !include integrations/cleaning/roomba_config.yaml
vera: !include integrations/zwave/vera_config.yaml
zwave: !include integrations/zwave/zwave_config.yaml
