###
# Device Tracker Settings
###
- platform: quantum_gateway
  host: !secret router_host
  # username: !secret router_user
  password: !secret router_password
  consider_home: 0:05
  new_device_defaults:
    track_new_devices: false
# - platform: ping
#   hosts:
#     ping_jose_iphone: !secret jphone_host
#     ping_jose_iwatch: !secret jwatch_host
#     ping_oren_pixel_3: !secret ophone_host
#     ping_roomba_890_maria: !secret roomba_host
#     ping_test_iphone_8: !secret test_iphone_host

# - platform: nmap_tracker
#   hosts: 192.168.1.0/24
