###
# Device Tracker Settings
###
- platform: quantum_gateway
  host: !secret router_host
  # username: !secret router_user
  password: !secret router_password
  consider_home: 0:05
  new_device_defaults:
    track_new_devices: false
- platform: ping
  hosts:
    jose_iphone: !secret jphone_host
    jose_iwatch: !secret jwatch_host
    oren_pixel_3: !secret ophone_host
    roomba_890_maria: !secret roomba_host
    test_iphone_8: !secret test_iphone_host
    # yariv_iphone: !secret yphone_host
    # yariv_iwatch: !secret ywatch_host
