harmonyhub:
  name: HarmonyHub
  mac: 00:04:20:F4:37:C0
  icon: mdi:remote-tv
  picture:
  track: true

841_hue_bridge:
  name: PhilipsHue
  mac: 00:17:88:23:91:28
  icon: mdi:bridge
  picture:
  track: true

drobo_5n:
  name: Drobo 5N
  mac: 00:1A:62:04:47:91
  icon: mdi:server
  picture:
  track: true

nest_thermo:
  name: LivingRoom_Nest
  mac: 18:B4:30:78:71:14
  icon: mdi:thermostat
  picture:
  track: true

jose_studio:
  name: Jose-Studio
  mac: 18:FF:0F:34:21:FE
  icon: mdi:laptop
  picture:
  track: true

xbox_series_x:
  name: XboxSeriesX
  mac: 1C:1A:DF:71:C4:14
  icon: mdi:microsoft-xbox
  picture:
  track: true

echo_dot:
  name: Echo Dot
  mac: 44:65:0D:31:8A:60
  icon: mdi:microphone
  picture:
  track: true

livingroom_chromecast:
  name: LivingRoomCast
  mac: 54:60:09:46:34:7C
  icon: mdi:google-chrome
  picture:
  track: true

roomba_maria:
  name: RoombaMaria
  mac: 80:C5:F2:39:B2:64
  icon: mdi:robot-vacuum
  picture:
  track: true

epson_printer:
  name: EPSONPrinter
  mac: B0:E8:92:0A:A6:45
  icon: mdi:printer
  picture:
  track: true

#### TODO
unknown_be_9a_b4_f5_21_77:
  name: unknown_be:9a:b4:f5:21:77
  mac: BE:9A:B4:F5:21:77
  icon:
  picture:
  track: true

viziotv:
  name: VizioTV
  mac: C4:1C:FF:40:5E:C0
  icon: mdi:television
  picture:
  track: true

homeassistant:
  name: homeassistant
  mac: DC:A6:32:37:A7:D5
  icon: mdi:home-assistant
  picture:
  track: true

echo_mb:
  name: MB_Alexa
  mac: F0:27:2D:62:2C:47
  icon: mdi:microphone
  picture:
  track: true

pixel_7_pro:
  name: OrenPixelPro
  mac: FA:F4:26:6B:86:67
  icon: mdi:cellphone
  picture:
  track: true

stormtrooper_wifi:
  name: StormtrooperWiFi
  mac: 6C:6A:77:E4:1B:F0
  icon: mdi:desktop-tower
  picture:
  track: true

#### TODO
unknown_be_ec_fd_78_5e_a7:
  name: unknown_be:ec:fd:78:5e:a7
  mac: BE:EC:FD:78:5E:A7
  icon:
  picture:
  track: true

fb_br30_1:
  name: FB-BR30-1
  mac: D0:73:D5:6C:EE:8D
  icon: mdi:lightbulb-outline
  picture:
  track: true

fb_br30_2:
  name: FB-BR30-2
  mac: D0:73:D5:6C:EF:60
  icon: mdi:lightbulb-outline
  picture:
  track: true

xbox_one_elite:
  name: XboxOneElite
  mac: 98:5F:D3:90:8B:3D
  icon: mdi:microsoft-xbox
  picture:
  track: true

livingroom_chromecast_audio:
  name: LivingRoomCastAudio
  mac: A4:77:33:F2:7B:74
  icon: mdi:cast-audio
  picture:
  track: true

sony_bravia_tv:
  name: SonyBravia
  mac: 70:18:8B:D1:03:64
  icon: mdi:television
  picture:
  track: true

kitchen_google_home:
  name: KitchenHome
  mac: F4:F5:D8:B4:ED:EC
  icon: mdi:microphone
  picture:
  track: true

nintendo_switch_oled:
  name: SwitchOLED
  mac: 80:D2:E5:69:CE:BA
  icon: mdi:nintendo-switch
  picture:
  track: true

marys_pixel_7_pro:
  name: Marys-Pixel-7-Pro
  mac: C6:E7:C8:8A:C0:33
  icon: mdi:cellphone
  picture:
  track: true

playstation_4:
  name: Playstation4
  mac: A8:47:4A:85:D8:B5
  icon: mdi:sony-playstation
  picture:
  track: true

fb_fan_1:
  name: FB-FAN-1
  mac: D0:73:D5:62:BC:65
  icon: mdi:lightbulb-outline
  picture:
  track: true

f_bath_1:
  name: F-Bath-1
  mac: D0:73:D5:5B:4B:9A
  icon: mdi:lightbulb-outline
  picture:
  track: true

f_bath_2:
  name: F-Bath-2
  mac: D0:73:D5:5B:9A:ED
  icon: mdi:lightbulb-outline
  picture:
  track: true

fb_br30_3:
  name: FB-BR30-3
  mac: D0:73:D5:6B:4D:6D
  icon:
  picture:
  track: true

fb_br30_4:
  name: FB-BR30-4
  mac: D0:73:D5:6C:8D:4B
  icon:
  picture:
  track: true

anova_cooker:
  name: AnovaSousVide
  mac: A0:20:A6:2F:68:99
  icon: mdi:pot-steam
  picture:
  track: true

orens_iphone:
  name: Orens-iPhone
  mac: E4:9A:DC:71:89:95
  icon: mdi:cellphone
  picture:
  track: true

jose_iphone:
  name: JoseiPhone
  mac: A0:4E:CF:EB:DE:10
  icon: mdi:cellphone
  picture:
  track: true

unknown_7a_9c_34_0a_51_0a:
  name: unknown_7a:9c:34:0a:51:0a
  mac: 7A:9C:34:0A:51:0A
  icon:
  picture:
  track: true

unknown_ca_37_22_1d_10_0f:
  name: unknown_ca:37:22:1d:10:0f
  mac: CA:37:22:1D:10:0F
  icon:
  picture:
  track: true

unknown_5c_0c_e6_f1_42_d8:
  name: unknown_5c:0c:e6:f1:42:d8
  mac: 5C:0C:E6:F1:42:D8
  icon:
  picture:
  track: true

02_37_24_e2_e0_13:
  name: 02_37_24_e2_e0_13
  mac: 02:37:24:E2:E0:13
  icon:
  picture:
  track: true

pixel_7_pro_2:
  name: Pixel-7-Pro
  mac: 0C:C4:13:42:8E:5B
  icon:
  picture:
  track: true

unknown_f2_29_5e_58_54_d0:
  name: unknown_f2:29:5e:58:54:d0
  mac: F2:29:5E:58:54:D0
  icon:
  picture:
  track: true

macbook_pro:
  name: MacBook-Pro
  mac: 5C:E9:1E:82:5E:09
  icon:
  picture:
  track: true

unknown_a2_b0_e3_60_29_8a:
  name: unknown_a2:b0:e3:60:29:8a
  mac: A2:B0:E3:60:29:8A
  icon:
  picture:
  track: true

unknown_56_66_a6_5a_8a_f8:
  name: unknown_56:66:a6:5a:8a:f8
  mac: 56:66:A6:5A:8A:F8
  icon:
  picture:
  track: true

unknown_a2_d4_af_d1_29_30:
  name: unknown_a2:d4:af:d1:29:30
  mac: A2:D4:AF:D1:29:30
  icon:
  picture:
  track: true

unknown_fe_1f_3e_08_67_d3:
  name: unknown_fe:1f:3e:08:67:d3
  mac: FE:1F:3E:08:67:D3
  icon:
  picture:
  track: true

unknown_b6_ab_5d_96_ce_39:
  name: unknown_b6:ab:5d:96:ce:39
  mac: B6:AB:5D:96:CE:39
  icon:
  picture:
  track: true

unknown_06_13_bc_b9_b6_d5:
  name: unknown_06:13:bc:b9:b6:d5
  mac: 06:13:BC:B9:B6:D5
  icon:
  picture:
  track: true

unknown_e6_f0_32_98_ad_01:
  name: unknown_e6:f0:32:98:ad:01
  mac: E6:F0:32:98:AD:01
  icon:
  picture:
  track: true

iphone:
  name: iPhone
  mac: 44:4A:DB:08:28:C4
  icon:
  picture:
  track: true

unknown_3a_dc_b3_52_58_7a:
  name: unknown_3a:dc:b3:52:58:7a
  mac: 3A:DC:B3:52:58:7A
  icon:
  picture:
  track: true

unknown_16_1b_c0_20_ac_f1:
  name: unknown_16:1b:c0:20:ac:f1
  mac: 16:1B:C0:20:AC:F1
  icon:
  picture:
  track: true

unknown_d4_f0_57_9f_12_1f:
  name: unknown_d4:f0:57:9f:12:1f
  mac: D4:F0:57:9F:12:1F
  icon:
  picture:
  track: true

unknown_ea_cb_a1_52_52_cc:
  name: unknown_ea:cb:a1:52:52:cc
  mac: EA:CB:A1:52:52:CC
  icon:
  picture:
  track: true

viziocastdisplay:
  name: viziocastdisplay
  mac: A4:8D:3B:38:CC:62
  icon:
  picture:
  track: true

unknown_7e_8a_0a_a2_31_c4:
  name: unknown_7e:8a:0a:a2:31:c4
  mac: 7E:8A:0A:A2:31:C4
  icon:
  picture:
  track: true

unknown_f2_df_9c_f3_36_d2:
  name: unknown_f2:df:9c:f3:36:d2
  mac: F2:DF:9C:F3:36:D2
  icon:
  picture:
  track: true

laptop_oddgqlks:
  name: LAPTOP-ODDGQLKS
  mac: 84:5C:F3:3C:D0:66
  icon:
  picture:
  track: true

unknown_ca_d4_06_2f_06_fa:
  name: unknown_ca:d4:06:2f:06:fa
  mac: CA:D4:06:2F:06:FA
  icon:
  picture:
  track: true

unknown_8a_20_c6_47_f4_9a:
  name: unknown_8a:20:c6:47:f4:9a
  mac: 8A:20:C6:47:F4:9A
  icon:
  picture:
  track: true

unknown_6a_e6_cf_27_77_b3:
  name: unknown_6a:e6:cf:27:77:b3
  mac: 6A:E6:CF:27:77:B3
  icon:
  picture:
  track: true

unknown_3a_cc_13_fe_e1_5c:
  name: unknown_3a:cc:13:fe:e1:5c
  mac: 3A:CC:13:FE:E1:5C
  icon:
  picture:
  track: true

rachelsiphone4:
  name: RachelsiPhone4
  mac: 30:D5:3E:13:7E:3C
  icon:
  picture:
  track: true

unknown_fe_7a_bc_53_12_6b:
  name: unknown_fe:7a:bc:53:12:6b
  mac: FE:7A:BC:53:12:6B
  icon:
  picture:
  track: true

watch_6:
  name: Watch
  mac: 92:70:CE:71:F4:A8
  icon:
  picture:
  track: true

unknown_3a_27_b0_1b_ff_d8:
  name: unknown_3a:27:b0:1b:ff:d8
  mac: 3A:27:B0:1B:FF:D8
  icon:
  picture:
  track: true

watch_7:
  name: Watch
  mac: 62:33:9D:9B:44:EB
  icon:
  picture:
  track: true

unknown_02_8c_09_d1_0d_12:
  name: unknown_02:8c:09:d1:0d:12
  mac: 02:8C:09:D1:0D:12
  icon:
  picture:
  track: true

watch_8:
  name: Watch
  mac: C2:74:F4:97:34:65
  icon:
  picture:
  track: true

watch_9:
  name: Watch
  mac: 4A:38:19:02:70:A8
  icon:
  picture:
  track: true

watch_10:
  name: Watch
  mac: 36:1E:02:94:23:77
  icon:
  picture:
  track: true

unknown_ee_d4_0f_82_d1_8c:
  name: unknown_ee:d4:0f:82:d1:8c
  mac: EE:D4:0F:82:D1:8C
  icon:
  picture:
  track: true

unknown_04_09_86_01_0d_89:
  name: unknown_04:09:86:01:0d:89
  mac: 04:09:86:01:0D:89
  icon:
  picture:
  track: true

unknown_1c_98_c1_01_c4_3c:
  name: unknown_1c:98:c1:01:c4:3c
  mac: 1C:98:C1:01:C4:3C
  icon:
  picture:
  track: true

mac:
  name: Mac
  mac: 5A:36:C9:97:F4:67
  icon:
  picture:
  track: true

pixel_7_pro_3:
  name: Pixel-7-Pro
  mac: 62:C6:07:60:81:C6
  icon:
  picture:
  track: true

levoit_humidifier:
  name: Levoit-Humidifier
  mac: 78:EE:4C:2D:84:BC
  icon:
  picture:
  track: true

lgwebostv:
  name: LGwebOSTV
  mac: 84:A3:29:85:00:9E
  icon:
  picture:
  track: true

bedroom:
  name: Bedroom
  mac: A4:CF:99:AF:47:30
  icon:
  picture:
  track: true

iphone_2:
  name: iPhone
  mac: CE:BD:1C:34:50:16
  icon:
  picture:
  track: true

unknown_7e_77_b7_56_da_07:
  name: unknown_7e:77:b7:56:da:07
  mac: 7E:77:B7:56:DA:07
  icon:
  picture:
  track: true

iphone_3:
  name: iPhone
  mac: A6:48:67:BC:28:26
  icon:
  picture:
  track: true

watch:
  name: Watch
  mac: C6:E6:AD:18:68:C6
  icon:
  picture:
  track: true

iphone_4:
  name: iPhone
  mac: 76:AE:B2:3E:20:67
  icon:
  picture:
  track: true

watch_2:
  name: Watch
  mac: C6:1D:EB:65:37:4D
  icon:
  picture:
  track: true

unknown_1e_2d_86_1e_05_24:
  name: unknown_1e:2d:86:1e:05:24
  mac: 1E:2D:86:1E:05:24
  icon:
  picture:
  track: true

watch_3:
  name: Watch
  mac: 82:86:46:BE:F7:13
  icon:
  picture:
  track: true

watch_4:
  name: Watch
  mac: 42:03:19:FC:1E:47
  icon:
  picture:
  track: true

win_i5rj39tppoe:
  name: WIN-I5RJ39TPPOE
  mac: C0:4B:24:F0:9B:9E
  icon:
  picture:
  track: true

win_i5rj39tppoe_2:
  name: WIN-I5RJ39TPPOE
  mac: C8:FF:BF:00:27:F9
  icon:
  picture:
  track: true

garmin_edge_1040_0f03ce970f03:
  name: garmin-Edge-1040-0f03ce970f03
  mac: 38:F9:F5:5E:B5:55
  icon:
  picture:
  track: true

watch_5:
  name: Watch
  mac: F2:05:54:05:9A:15
  icon:
  picture:
  track: true

iphone_5:
  name: iPhone
  mac: E6:6A:20:19:FD:1A
  icon:
  picture:
  track: true

watch_11:
  name: Watch
  mac: A2:42:FC:15:8C:3F
  icon:
  picture:
  track: true

unknown_fe_35_0a_e9_47_ca:
  name: unknown_fe:35:0a:e9:47:ca
  mac: FE:35:0A:E9:47:CA
  icon:
  picture:
  track: true

watch_12:
  name: Watch
  mac: 42:A0:CE:47:69:86
  icon:
  picture:
  track: true

watch_13:
  name: Watch
  mac: 46:09:D4:CB:D4:57
  icon:
  picture:
  track: true

watch_14:
  name: Watch
  mac: C6:F5:F3:11:00:B4
  icon:
  picture:
  track: true

watch_15:
  name: Watch
  mac: EE:A6:FD:19:5D:68
  icon:
  picture:
  track: true

watch_16:
  name: Watch
  mac: 3A:ED:A7:D7:17:69
  icon:
  picture:
  track: true

watch_17:
  name: Watch
  mac: 4A:0C:DF:32:FC:4E
  icon:
  picture:
  track: true

watch_18:
  name: Watch
  mac: A2:B1:0A:BE:DA:E6
  icon:
  picture:
  track: true

unknown_9a_17_70_3c_1c_08:
  name: unknown_9a:17:70:3c:1c:08
  mac: 9A:17:70:3C:1C:08
  icon:
  picture:
  track: true

watch_19:
  name: Watch
  mac: 4E:9E:33:DE:40:9F
  icon:
  picture:
  track: true

watch_20:
  name: Watch
  mac: 7E:35:9F:B7:E5:F9
  icon:
  picture:
  track: true

watch_21:
  name: Watch
  mac: 2A:62:AB:70:93:86
  icon:
  picture:
  track: true

iphone_6:
  name: iPhone
  mac: 16:EC:D6:D2:2A:D8
  icon:
  picture:
  track: true

watch_22:
  name: Watch
  mac: 42:EF:27:21:C5:96
  icon:
  picture:
  track: true

watch_23:
  name: Watch
  mac: 1E:75:B6:79:14:37
  icon:
  picture:
  track: true

watch_24:
  name: Watch
  mac: 9E:CB:18:AE:7F:41
  icon:
  picture:
  track: true

watch_25:
  name: Watch
  mac: 22:96:3B:35:13:AE
  icon:
  picture:
  track: true

iphone_7:
  name: iPhone
  mac: AE:8F:A9:98:8D:7E
  icon:
  picture:
  track: true

unknown_3c_a9_ab_7b_03_b0:
  name: unknown_3c:a9:ab:7b:03:b0
  mac: 3C:A9:AB:7B:03:B0
  icon:
  picture:
  track: true

julians_mbp_2:
  name: Julians-MBP-2
  mac: 9C:3E:53:8C:E6:E7
  icon:
  picture:
  track: true

unknown_0a_ff_bd_89_d1_6b:
  name: unknown_0a:ff:bd:89:d1:6b
  mac: 0A:FF:BD:89:D1:6B
  icon:
  picture:
  track: true

iphone_8:
  name: iPhone
  mac: 5A:57:6F:C7:B3:71
  icon:
  picture:
  track: true

homeassistant_2:
  name: homeassistant
  mac: 20:F8:3B:01:70:2C
  icon:
  picture:
  track: true

ipad:
  name: iPad
  mac: 92:12:90:DD:8F:33
  icon:
  picture:
  track: true

unknown_a2_3c_2e_c3_f8_bd:
  name: unknown_a2:3c:2e:c3:f8:bd
  mac: A2:3C:2E:C3:F8:BD
  icon:
  picture:
  track: true

huesyncbox_c42996e1b600:
  name: HueSyncBox-C42996E1B600
  mac: C4:29:96:E1:B6:00
  icon:
  picture:
  track: true

unknown_10_ae_60_ee_b8_3e:
  name: unknown_10:ae:60:ee:b8:3e
  mac: 10:AE:60:EE:B8:3E
  icon:
  picture:
  track: true

watch_26:
  name: Watch
  mac: AA:60:1B:EC:F4:D4
  icon:
  picture:
  track: true

watch_27:
  name: Watch
  mac: 1E:60:97:94:21:59
  icon:
  picture:
  track: true

iphone_9:
  name: iPhone
  mac: 68:EF:DC:51:F0:44
  icon:
  picture:
  track: true

iphone_10:
  name: iPhone
  mac: 76:FC:15:89:09:F8
  icon:
  picture:
  track: true

watch_28:
  name: Watch
  mac: 32:A9:DA:97:28:82
  icon:
  picture:
  track: true

watch_29:
  name: Watch
  mac: AA:75:EB:AE:05:62
  icon:
  picture:
  track: true

iphone_11:
  name: iPhone
  mac: 0A:38:5B:4E:AD:5D
  icon:
  picture:
  track: true

watch_30:
  name: Watch
  mac: 62:37:1E:DB:03:09
  icon:
  picture:
  track: true

unknown_de_1f_87_d1_b2_27:
  name: unknown_de:1f:87:d1:b2:27
  mac: DE:1F:87:D1:B2:27
  icon:
  picture:
  track: true

watch_31:
  name: Watch
  mac: 32:9D:36:90:85:D7
  icon:
  picture:
  track: true

watch_32:
  name: Watch
  mac: 9E:AA:77:E1:F3:26
  icon:
  picture:
  track: true

watch_33:
  name: Watch
  mac: 22:E4:B7:2C:C8:B2
  icon:
  picture:
  track: true

watch_34:
  name: Watch
  mac: 52:80:3D:0E:F1:72
  icon:
  picture:
  track: true

watch_35:
  name: Watch
  mac: FE:07:A5:68:66:17
  icon:
  picture:
  track: true

watch_36:
  name: Watch
  mac: 7E:31:AF:8F:1E:D8
  icon:
  picture:
  track: true

watch_37:
  name: Watch
  mac: 4E:EC:46:55:1A:E7
  icon:
  picture:
  track: true

iphone_12:
  name: iPhone
  mac: 72:B6:5D:69:2B:01
  icon:
  picture:
  track: true

watch_38:
  name: Watch
  mac: 86:11:0E:0D:AF:46
  icon:
  picture:
  track: true

watch_39:
  name: Watch
  mac: A6:9E:6D:64:67:9A
  icon:
  picture:
  track: true

unknown_de_0c_7d_a8_0d_b6:
  name: unknown_de:0c:7d:a8:0d:b6
  mac: DE:0C:7D:A8:0D:B6
  icon:
  picture:
  track: true

watch_40:
  name: Watch
  mac: 92:FB:B1:0D:60:4D
  icon:
  picture:
  track: true

watch_41:
  name: Watch
  mac: 46:30:1C:DE:66:76
  icon:
  picture:
  track: true

unknown_ae_a5_61_9d_08_2e:
  name: unknown_ae:a5:61:9d:08:2e
  mac: AE:A5:61:9D:08:2E
  icon:
  picture:
  track: true

unknown_7a_41_a1_5f_1e_44:
  name: unknown_7a:41:a1:5f:1e:44
  mac: 7A:41:A1:5F:1E:44
  icon:
  picture:
  track: true

pixel_10_pro_fold:
  name: Pixel-10-Pro-Fold
  mac: 0A:21:81:0D:B2:E1
  icon:
  picture:
  track: true

unknown_24_fd_fa_17_f6_45:
  name: unknown_24:fd:fa:17:f6:45
  mac: 24:FD:FA:17:F6:45
  icon:
  picture:
  track: true

watch_42:
  name: Watch
  mac: 9E:C3:14:C6:DE:2F
  icon:
  picture:
  track: true

watch_43:
  name: Watch
  mac: FA:55:A2:69:83:A6
  icon:
  picture:
  track: true

watch_44:
  name: Watch
  mac: 66:9F:12:00:CC:F8
  icon:
  picture:
  track: true

watch_45:
  name: Watch
  mac: 0A:99:B0:46:88:7D
  icon:
  picture:
  track: true

watch_46:
  name: Watch
  mac: EA:6C:63:98:F5:C4
  icon:
  picture:
  track: true

watch_47:
  name: Watch
  mac: AA:0C:8A:FA:4E:A8
  icon:
  picture:
  track: true

watch_48:
  name: Watch
  mac: 36:08:4F:CE:5C:95
  icon:
  picture:
  track: true

watch_49:
  name: Watch
  mac: 56:4D:2D:6D:88:0E
  icon:
  picture:
  track: true

watch_50:
  name: Watch
  mac: FA:D7:3A:B9:E5:57
  icon:
  picture:
  track: true

watch_51:
  name: Watch
  mac: 4E:0F:57:56:7E:97
  icon:
  picture:
  track: true

unknown_56_9f_6a_d1_cc_12:
  name: unknown_56:9f:6a:d1:cc:12
  mac: 56:9F:6A:D1:CC:12
  icon:
  picture:
  track: true
