##################
# Infrastructure #
##################
honeywell_lyric:
  name: Honeywell Thermostat
  mac: B8:2C:A0:00:FB:BD
  icon: mdi:thermostat-box
  picture:
  track: false

apple_device:
  name: Unknown Apple Device
  mac: 88:66:5A:10:B5:47
  icon: mdi:apple
  picture:
  track: false

homeassistant:
  name: homeassistant
  mac: DC:A6:32:7F:C4:BF
  icon: mdi:home-assistant
  picture:
  track: false

yamaha_receiver:
  name: Living Room Receiver
  mac: 00:A0:DE:71:69:76
  icon: mdi:audio-video
  picture:
  track: false

nvidia_shield:
  name: Nvidia Shield
  mac: 00:04:4B:CD:1D:DE
  icon: mdi:television-shimmer
  picture:
  track: false

chromecast:
  name: Chromecast
  mac: A4:77:33:01:B2:5B
  icon: mdi:google-chrome
  picture:
  track: false

harmonyhub:
  name: Harmony Hub
  mac: C8:DB:26:0A:7F:EC
  icon: mdi:remote-tv
  picture:
  track: false

chromecast_2:
  name: Chromecast 2
  mac: 14:C1:4E:67:27:71
  icon: mdi:google-chrome
  picture:
  track: false

mary_laptop:
  name: Mom's Lenovo
  mac: 84:5C:F3:3C:D0:66
  icon: mdi:laptop
  picture:
  track: false

howies_iphone:
  name: Howies iPhone
  mac: 42:25:F9:69:97:0E
  icon:
  picture:
  track: false

mary_pixel_3:
  name: Mom's Pixel 3
  mac: EE:81:BD:5E:97:7D
  icon: mdi:cellphone
  picture:
  track: false

amazon_devices:
  name: Amazon Device
  mac: 08:84:9D:D9:4A:F9
  icon: mdi:aws
  picture:
  track: false

lgwebostv:
  name: LGwebOSTV
  mac: 18:82:8C:45:37:C6
  icon:
  picture:
  track: false
