##################
# Infrastructure #
##################
honeywell_lyric:
  name: Honeywell Thermostat
  mac: B8:2C:A0:00:FB:BD
  icon: mdi:thermostat-box
  picture:
  track: false

homeassistant:
  name: homeassistant
  mac: DC:A6:32:7F:C4:BF
  icon: mdi:home-assistant
  picture:
  track: false

yamaha_receiver:
  name: Living Room Receiver
  mac: 00:A0:DE:71:69:76
  icon: mdi:audio-video
  picture:
  track: false

nvidia_shield:
  name: Nvidia Shield
  mac: 00:04:4B:CD:1D:DE
  icon: mdi:television-shimmer
  picture:
  track: false

chromecast:
  name: Chromecast
  mac: A4:77:33:01:B2:5B
  icon: mdi:google-chrome
  picture:
  track: false

harmonyhub:
  name: Harmony Hub
  mac: C8:DB:26:0A:7F:EC
  icon: mdi:remote-tv
  picture:
  track: false

chromecast_2:
  name: Chromecast 2
  mac: 14:C1:4E:67:27:71
  icon: mdi:google-chrome
  picture:
  track: false

amazon_devices:
  name: Amazon Device
  mac: 08:84:9D:D9:4A:F9
  icon: mdi:aws
  picture:
  track: false

lg_tv_kitchen:
  name: Kitchen TV
  mac: 18:82:8C:45:37:C6
  icon: mdi:television
  picture:
  track: false

apple_device:
  name: Unknown Apple Device
  mac: 88:66:5A:10:B5:47
  icon: mdi:apple
  picture:
  track: false

samsung_tv:
  name: Samsung TV
  mac: FC:8F:90:40:0D:1F
  icon: mdi:television
  picture:
  track: false

samsung_tv_2:
  name: Samsung TV 2
  mac: 28:39:5E:59:43:4A
  icon: mdi:television
  picture:
  track: false

# Mom:
mary_laptop:
  name: Mom's Lenovo
  mac: 84:5C:F3:3C:D0:66
  icon: mdi:laptop
  picture:
  track: false

mary_pixel_3:
  name: Mom's Pixel 3a
  mac: 5E:97:70:F3:C1:0D
  icon: mdi:android
  picture:
  track: true

# Dad:
howies_iphone:
  name: Howie's iPhone
  mac: 42:25:F9:69:97:0E
  icon: mdi:iphone
  picture:
  track: true

chop_mbp:
  name: CHOP MBP
  mac: F0:2F:4B:10:5B:7D
  icon: mdi:laptop
  picture:
  track: false

# Oren
pixel_3_oren:
  name: Pixel 3
  mac: 3C:28:6D:2C:E3:5D
  icon: mdi:android
  picture:
  track: true

startree_mbp:
  name: StarTree MBP
  mac: 88:66:5A:0A:9D:14
  icon: mdi:laptop
  picture:
  track: false

# Becky
becky_mbp:
  name: Rebecca's MBP
  mac: 14:7D:DA:07:96:0D
  icon: mdi:laptop
  picture:
  track: false

# John
johns_air:
  name: Johns Air
  mac: 30:35:AD:AB:2F:DE
  icon: mdi:laptop
  picture:
  track: true

# Others
jackieswatch:
  name: Jackies Apple Watch
  mac: 10:CE:E9:DB:34:EA
  icon: mdi:watch
  picture:
  track: false

c4_14_11_79_f0_62:
  name: C4:14:11:79:F0:62
  mac: C4:14:11:79:F0:62
  icon: mdi:iphone
  picture:
  track: true

ec_ad_b8_62_42_10:
  name: EC:AD:B8:62:42:10
  mac: EC:AD:B8:62:42:10
  icon: mdi:iphone
  picture:
  track: true

nintendo_switch_1:
  name: Nintendo Switch 1
  mac: 98:B6:E9:B3:FA:B0
  icon: mdi:nintendo
  picture:
  track: true

ginas_iphone:
  name: Ginas-iPhone
  mac: 08:87:C7:01:83:F4
  icon: mdi:iphone
  picture:
  track: true
