##################
# Infrastructure #
##################
honeywell_lyric:
  name: Honeywell Thermostat
  mac: B8:2C:A0:00:FB:BD
  icon: mdi:thermostat-box
  picture:
  track: false

apple_device:
  name: Unknown Apple Device
  mac: 88:66:5A:10:B5:47
  icon: mdi:apple
  picture:
  track: false

homeassistant:
  name: homeassistant
  mac: DC:A6:32:7F:C4:BF
  icon: mdi:home-assistant
  picture:
  track: false

yamaha_receiver:
  name: Living Room Receiver
  mac: 00:A0:DE:71:69:76
  icon: mdi:audio-video
  picture:
  track: false

nvidia_shield:
  name: Nvidia Shield
  mac: 00:04:4B:CD:1D:DE
  icon: mdi:television-shimmer
  picture:
  track: false

chromecast:
  name: Chromecast
  mac: A4:77:33:01:B2:5B
  icon: mdi:google-chrome
  picture:
  track: false

harmonyhub:
  name: Harmony Hub
  mac: C8:DB:26:0A:7F:EC
  icon: mdi:remote-tv
  picture:
  track: false

chromecast_2:
  name: Chromecast 2
  mac: 14:C1:4E:67:27:71
  icon: mdi:google-chrome
  picture:
  track: false

mary_laptop:
  name: Mom's Lenovo
  mac: 84:5C:F3:3C:D0:66
  icon: mdi:laptop
  picture:
  track: false

howies_iphone:
  name: Howies iPhone
  mac: 42:25:F9:69:97:0E
  icon:
  picture:
  track: false

mary_pixel_3:
  name: Mom's Pixel 3
  mac: EE:81:BD:5E:97:7D
  icon: mdi:cellphone
  picture:
  track: false

amazon_devices:
  name: Amazon Device
  mac: 08:84:9D:D9:4A:F9
  icon: mdi:aws
  picture:
  track: false

lgwebostv:
  name: LGwebOSTV
  mac: 18:82:8C:45:37:C6
  icon:
  picture:
  track: false

b6_d2_e4_cd_8b_55:
  name: B6:D2:E4:CD:8B:55
  mac: B6:D2:E4:CD:8B:55
  icon:
  picture:
  track: true

jackiesplewatch:
  name: JackiespleWatch
  mac: 10:CE:E9:DB:34:EA
  icon:
  picture:
  track: true

52_19_3f_0f_9f_47:
  name: 52:19:3F:0F:9F:47
  mac: 52:19:3F:0F:9F:47
  icon:
  picture:
  track: true

c4_14_11_79_f0_62:
  name: C4:14:11:79:F0:62
  mac: C4:14:11:79:F0:62
  icon:
  picture:
  track: true

ec_ad_b8_62_42_10:
  name: EC:AD:B8:62:42:10
  mac: EC:AD:B8:62:42:10
  icon:
  picture:
  track: true

2a_41_93_5b_3a_e7:
  name: 2A:41:93:5B:3A:E7
  mac: 2A:41:93:5B:3A:E7
  icon:
  picture:
  track: true
