###
# Config file for Profiles in the House
###
- name: Oren
  id: opanit001
  user_id: c300943f016f44b9af2cf180d706fcb7
  device_trackers:
    - device_tracker.pixel_3
- name: Jose
  id: jvazque001
  # user_id: e460d8e3f77f43c0a56c3295f9b61dcf
  device_trackers:
    - device_tracker.jose_iphone