###
# Config file for People tracked in the House
# https://www.home-assistant.io/integrations/person/
###
- name: Hal
  id: !secret hal_id
  device_trackers:
    - device_tracker.hals_air
- name: Drama
  id: !secret drama_id
  device_trackers:
    - device_tracker.jacob_ipad
    - device_tracker.jacob_nintendo_switch
- name: Hermes
  id: !secret hermes_id
  user_id: !secret hermes_user_id
- name: Jake
  id: !secret jake_id
  device_trackers:
    - device_tracker.jake_iphone
- name: Jose
  id: !secret jose_id
  user_id: !secret jose_user_id
  device_trackers:
    - device_tracker.jose_galaxy_tab
    - device_tracker.jose_iphone
    - device_tracker.jose_laptop
    - device_tracker.jose_laptop_work
- name: Nate
  id: !secret nate_id
  device_trackers:
    - device_tracker.nate_iphone
    - device_tracker.nate_mbp
- name: Oren
  id: !secret oren_id
  user_id: !secret oren_user_id
  device_trackers:
    - device_tracker.comcast_mbp
    - device_tracker.oren_pixel_3
    - device_tracker.oren_switch
- name: Yariv
  id: !secret yariv_id
  device_trackers:
    - device_tracker.yariv_ipad
    - device_tracker.yariv_iphone
    - device_tracker.yariv_mbp
    - device_tracker.yariv_nintendo_switch
    - device_tracker.yariv_oculus
