title: 841 N 4th
# views: !include_dir_merge_list views/
views:
  - !include views/overview-view.yaml
  - !include views/kitchen-view.yaml
  - !include views/living-room-view.yaml
  - !include views/master-suite.yaml
  - !include views/second-bedroom-view.yaml
  - !include views/exterior-view.yaml
