# Include external resources only add when resource_mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
# resources:
# resource_mode: yaml
# Add more dashboards
dashboards: !include_dir_named dashboards/
