mode: yaml
# Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
# resources:
# Add more dashboards
dashboards: !include_dir_named dashboards/
