light_group: light.living_room
light_profile: reading
device_group: group.household
disable_turn_off: false

###
# Presence-based Lights
# https://www.home-assistant.io/integrations/device_sun_light_trigger/
###