##
# Yamaha Receiver Config - living room
##
# - platform: yamaha
#   host: !secret yamaha_receiver_host
#   source_names:
#     HDMI1: "Xbox One"
#     HDMI2: "Chromecast"
#     HDMI3: "Switch"
#     AV1: "Turntable"
#     AV2: "ChromeAudio"