- platform: template
  sensors:
    maria_last_clean:
      friendly_name: Maria's Last Sweep
      device_class: timestamp
      value_template: >-
        {{states.vacuum.maria.status.last_changed | timestamp_local}}