host: !secret plex_server_host
port: !secret plex_server_port
token: !secret plex_server_token
server: Drobo5N
ssl: false
verify_ssl: false
media_player:
  use_episode_art: true
  ignore_new_shared_users: false